baseURL = 'https://dev.hacf.fr'
languageCode = 'fr-fr'
title = 'HACF'

#theme =
paginate = 6

enableRobotsTXT = true
enableEmoji = true

enableInlineShortcodes = true
enableGitInfo = true

[params]
  description = "Blog de la Communauté Francophone autour de Home Assistant et de son assocition."
  keywords = "Domotique, Home Assistant, Jeedom, Domoticz, Openhab, Gladys, Association HACF, Communauté Francophone"
  logo = "/images/logo.webp"
  #defaulthero =  "/images/articles/article.webp" #NON FONCTIONNEL
  contact = "https://framaforms.org/contacter-lassociation-ou-la-communaute-hacf-1630416579"
  mainSections = ["blog", "news"] #https://gohugo.io/functions/where/#mainsections
  customcss = true
  # Background image du jumbotron
  # background = '/images/site/background-dark.jpg'

  heightCode = "300px" # Recuperer la valeur a appliquer sur es blocs de code
  enableTOC = true

  # GitHub repo du site
  gitRepo = "https://github.com/McFlyPartages/hacf-blog"
  gitBranch = "main"

  gitRepoAwesome = "https://github.com/McFlyPartages/awesome-francophone-home-assistant"
  gitBranchAwesome = "main"

  gitRepoGuideDev = "https://github.com/McFlyPartages/homeassistant-guide-du-developpeur"
  gitBranchGuideDev = "main"
  
[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = ['lastmod', ':git', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[taxonomies]
  tag = 'tags'
  category = 'categories'
  series = 'series'
  author = 'authors'



[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'categories'
  weight = 60


[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
#resampleFilter = "box"
# Default JPEG or WebP quality setting. Default is 75.
quality = 100
hint = "photo"
disableDate = true
disableLatLong = true



[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

## Permet de supprimer les classes inutilisées dans le CSS et ainsi reduire sa taille. https://gohugo.io/hugo-pipes/postprocess/
[build]
  writeStats = true
